name: build-ios-tvos

on:
  push:
    paths-ignore:
    - '**/README.md'
  pull_request:
    paths-ignore:
    - '**/README.md'
    
jobs:

  build-osx:
    runs-on: macos-10.15
    strategy:
        matrix:
          cfg:
          - {target: ios, libs: ios}
          - {target: tvos, libs: ios}
    env:
     TARGET: ${{matrix.cfg.target}}
    steps:
    - uses: actions/checkout@v2
    - name: Download libs
      run: ./scripts/${{matrix.cfg.libs}}/download_libs.sh
    - name: install
      run: ./scripts/ci/$TARGET/install.sh
    - name: Build
      run: ./scripts/ci/$TARGET/build.sh;

      env:
        DEVELOPER_DIR: "/Applications/Xcode_11.2.app/Contents/Developer"

