name: nightly-linux64

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-linux-platforms:
    runs-on: ubuntu-20.04
    strategy:
        matrix:
          cfg:
          - {target: linux64, libs: 64gcc6}
    env:
     TARGET: ${{matrix.cfg.target}}
    steps:
    - uses: actions/checkout@v3
    - name: Download libs
      run: ./scripts/linux/download_libs.sh -a ${{matrix.cfg.libs}};
    - name: Install dependencies
      run: ./scripts/ci/$TARGET/install.sh;
    - name: Create Package
      run: scripts/ci/package_builds.sh;
    - name: Update Release
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: nightly
        release: nightly
        prerelease: false
        files: out/*.tar.bz2
      if: github.repository == 'ofTheo/openFrameworks' && github.event_name == 'push' && github.ref == 'refs/heads/nightly-release'

