name: build-msys2

on:
  push:
    paths-ignore:
    - '**/README.md'
  pull_request:
    paths-ignore:
    - '**/README.md'
    
jobs:

  build-msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        cfg:
        - {target: "MINGW32"}
        - {target: "MINGW64"}
    defaults:
      run:
        shell: msys2 {0}
    env: 
      MSYSTEM: ${{matrix.cfg.target}}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          unzip
          rsync
          wget
    - name: Install dependencies
      run:
        ./scripts/ci/msys2/install.sh
    - name: Build
      run:
        ./scripts/ci/msys2/build.sh
    - name: Run tests
      run:
        ./scripts/ci/msys2/run_tests.sh
    - name: Upload Libs
      run: scripts/ci/upload_of_lib.sh;
      env:
          GA_CI_SECRET: ${{ secrets.CI_SECRET }}
