name: build-linux64-and-arm

# make the action not run on the local repo if the branch is also in a pull request to OF/OF
on:
  push:
    if: github.event_name == 'push' && github.event.pull_request == null
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    if: github.event_name == 'pull_request' && github.repository == 'openframeworks/openFrameworks'
    paths-ignore:
      - '**/*.md'
      - 'examples/**'

    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Sysroot
        id: pi-sysroot
        uses: mariotaku/raspbian-sysroot-action@main
        with:
          # Can be space separated, multiline list or a file
          packages: libc6-dev libc6
      - name: Install Build Tools
        shell: bash
        run: sudo apt-get -y -qq install crossbuild-essential-armhf
      - uses: actions/checkout@v3
      - name: Download libs
        run: |
          ls -la /opt/
          ls -la /opt/pi-sysroot/
          ls -la /opt/pi-sysroot/usr/include/
          ls -la /opt/pi-sysroot/usr/include/arm-linux-gnueabihf/
          ./scripts/linux/download_libs.sh -a armv6l;
      - name: Build
        run: |
          source ${{steps.pi-sysroot.outputs.shell-envsetup}}
          scripts/ci/linuxarmv6l/build.sh;
