name: build-linux64-and-arm

# make the action not run on the local repo if the branch is also in a pull request to OF/OF
on:
  push:
    if: github.event_name == 'push' && github.event.pull_request == null
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    if: github.event_name == 'pull_request' && github.repository == 'openframeworks/openFrameworks'
    paths-ignore:
      - '**/*.md'
      - 'examples/**'

    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Sysroot
        id: pi-sysroot
        uses: mariotaku/raspbian-sysroot-action@main
        with:
          # Can be space separated, multiline list or a file
          packages: libunwind-dev libharfbuzz-dev gstreamer1.0-vaapi gstreamer1.0-libav freeglut3-dev libasound2-dev libxmu-dev libxxf86vm-dev g++ libgl1-mesa-dev libglu1-mesa-dev libraw1394-dev libudev-dev libdrm-dev libglew-dev libopenal-dev libsndfile-dev libfreeimage-dev libcairo2-dev libfreetype6-dev libssl-dev libpulse-dev libusb-1.0-0-dev libgtk3-dev libopencv-dev libgles1 libgles2-mesa-dev libassimp-dev librtaudio-dev libboost-filesystem-dev libglfw3-dev  liburiparser-dev libcurl4-openssl-dev libpugixml-dev libpoco-dev libgconf-2-4 libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev  ${GSTREAMER_FFMPEG} gstreamer1.0-pulseaudio gstreamer1.0-x gstreamer1.0-plugins-bad gstreamer1.0-alsa gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-omx gstreamer1.0-ffmpeg
      - name: Install Build Tools
        shell: bash
        run: sudo apt-get -y -qq install crossbuild-essential-armhf
      - uses: actions/checkout@v3
      - name: Download libs
        run: ./scripts/linux/download_libs.sh -a armv6l;
      - name: Build
        run: |
          source ${{steps.pi-sysroot.outputs.shell-envsetup}}
          scripts/ci/linuxarmv6l/build.sh;
