name: build-linux64-and-arm

# make the action not run on the local repo if the branch is also in a pull request to OF/OF
on:
  push:
    if: github.event_name == 'push' && github.event.pull_request == null
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    if: github.event_name == 'pull_request' && github.repository == 'openframeworks/openFrameworks'
    paths-ignore:
      - '**/*.md'
      - 'examples/**'

    
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Sysroot
        id: pi-sysroot
        uses: mariotaku/raspbian-sysroot-action@main
        with:
          # Can be space separated, multiline list or a file
          packages: freeglut3-dev
      - uses: actions/checkout@v3
      - name: Download libs
        run: ./scripts/linux/download_libs.sh -a armv6l;
      - name: Install packages 
        run: ./scripts/linux/scripts/linux/debian/install_dependencies.sh -y
      - name: Build
        run: scripts/ci/linuxarmv6l/build.sh;
