name: build-emscripten

# make the action not run on the local repo if the branch is also in a pull request to OF/OF
on: 
  workflow_dispatch:
    inputs:
          release:
            description: 'release'     
            required: true
            default: 'nightly'
jobs:
  build-emscripten:
    runs-on: ubuntu-20.04
    strategy:
        matrix:
          cfg:
          - {target: emscripten}
    env:
     TARGET: ${{matrix.cfg.target}}
    steps:
    - uses: actions/checkout@v4
    - name: Docker Step
      run:  "docker run -di --name emscripten -v $PWD:/src emscripten/emsdk:3.1.21 bash"
    - name: Download libs
      run: ./scripts/$TARGET/download_libs.sh
    - name: Install dependencies
      run: ./scripts/ci/$TARGET/install.sh
    - name: Build
      run: docker exec -i emscripten sh -c "scripts/ci/$TARGET/examples_to_build.sh";
      env:
          GA_CI_SECRET: ${{ secrets.CI_SECRET }}
