name: build-web-examples


# make the action not run on the local repo if the branch is also in a pull request to OF/OF
#on: 
#  workflow_dispatch:
#    inputs:
#          release:
#            description: 'release'     
#            required: true
#            default: 'nightly'
on:
  push:
    if: github.event_name == 'push' && github.event.pull_request == null
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    if: github.event_name == 'pull_request' && github.repository == 'openframeworks/openFrameworks'
    paths-ignore:
      - '**/*.md'
      - 'examples/**'
jobs:
  build-web-examples:
    runs-on: ubuntu-20.04
    strategy:
        matrix:
          cfg:
          - {target: emscripten}
    env:
     TARGET: ${{matrix.cfg.target}}
    steps:
    - uses: actions/checkout@v4
    - name: Docker Step
      run:  "docker run -di --name emscripten -v $PWD:/src emscripten/emsdk:3.1.21 bash"
    - name: Download libs
      run: ./scripts/$TARGET/download_libs.sh
    - name: Install dependencies
      run: ./scripts/ci/$TARGET/install.sh
    - name: Build
      run: docker exec -i emscripten sh -c "export GA_EXAMPLES_USER='${GA_EXAMPLES_USER}' \
        && export GA_EXAMPLES_SERVER='${GA_EXAMPLES_SERVER}' \
        && export GA_EXAMPLES_KEY='${GA_EXAMPLES_KEY}' \
        && export GH_HEAD_REF='${{ github.head_ref }}' \
        && export GH_BRANCH='${{ github.ref_name }}' \
        && export GH_ACTIONS='true' \
        && scripts/ci/$TARGET/examples_to_build.sh"
      env:
          GA_EXAMPLES_USER: ${{ secrets.SSH_USER }}
          GA_EXAMPLES_SERVER: ${{ secrets.SSH_SERVER }}
          GA_EXAMPLES_KEY: ${{ secrets.SSH_KEY }}
